//
//  HelloWorldText.swift
//  JustHelloWorld
//
//  Created by Murat Can KOÇ on 8.02.2022.
//

import Foundation

class HelloWorldText {
     static let textArray = [
        "Hello Wêreld!",
        "Përshendetje Botë!",
        "ሰላም ዓለም!",
        "مرحبا بالعالم!",
        "Բարեւ աշխարհ!",
        "Salam, Dünya!",
        "Kaixo Mundua!",
        "Прывітанне Сусвет!",
        "ওহে বিশ্ব!",
        "Zdravo svijete!",
        "Здравей свят!",
        "Hola món!",
        "Hello, Kalibutan!",
        "Moni Dziko Lapansi!",
        "你好世界！",
        "你好世界！",
        "Salutu, mondu !",
        "Pozdrav svijete!",
        "Ahoj světe!",
        "Hej Verden!",
        "Hallo Wereld!",
        "Hello World!",
        "Saluton mondo!",
        "Tere, Maailm!",
        "Hello Mundo!",
        "Hei maailma!",
        "Bonjour, le monde!",
        "Hallo wrâld!",
        "Ola mundo!",
        "გამარჯობა მსოფლიო!",
        "Hallo Welt!",
        "Γειά σου Κόσμε!",
        "હેલો વર્લ્ડ!",
        "Bonjou mond!",
        "Sannu Duniya!",
        "Aloha Honua!",
        "שלום עולם!",
        "हैलो वर्ल्ड!",
        "Nyob zoo ntiaj teb!",
        "Helló Világ!",
        "Halló heimur!",
        "Ndewo Ụwa!",
        "Halo Dunia!",
        "Dia duit Domhanda!",
        "Ciao mondo!",
        "こんにちは世界",
        "Hello World!",
        "ಹಲೋ ವರ್ಲ್ಡ್!",
        "Сәлем Әлем!",
        "សួស្តី​ពិភពលោក!",
        "Mwaramutse Isi!",
        "안녕하세요 월드입니다!",
        "Silav Cîhan!",
        "Салам дүйнө!",
        "ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!",
        "Salve Mundus!",
        "Sveika pasaule!",
        "Labas pasauli!",
        "Moien Welt!",
        "Здраво свету!",
        "Hello World!",
        "Hai dunia!",
        "ഹലോ വേൾഡ്!",
        "Hello dinja!",
        "Kia ora te Ao!",
        "हॅलो वर्ल्ड!",
        "Сайн уу Дэлхий!",
        "မင်္ဂလာပါကမ္ဘာလောက!",
        "नमस्कार संसार!",
        "Hei Verden!",
        "ନମସ୍କାର ବିଶ୍ୱବାସି!",
        "سلام دنیا!",
        "Witaj świecie!",
        "Olá Mundo!",
        "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
        "Salut Lume!",
        "Привет мир!",
        "Talofa le Lalolagi!",
        "Hàlo a Shaoghail!",
        "Здраво Свете!",
        "Lefatše Lumela!",
        "Mhoro Nyika!",
        "هيلو دنيا!",
        "හෙලෝ වර්ල්ඩ්!",
        "Ahoj svet!",
        "Pozdravljen, svet!",
        "Hello Adduunka!",
        "Hola Mundo!",
        "Halo Dunya!",
        "Salamu, Dunia!",
        "Hej världen!",
        "Салом Ҷаҳон!",
        "வணக்கம் உலகம்!",
        "Сәлам, Дөнья!",
        "హలో వరల్డ్!",
        "สวัสดีชาวโลก!",
        "Selam Dünya!",
        "Salam Dünýä!",
        "Привіт Світ!",
        "ہیلو ورلڈ!",
        "ياخشىمۇسىز دۇنيا!",
        "Salom Dunyo!",
        "Chào thế giới!",
        "Helo Byd!",
        "Molo Lizwe!",
        "העלא וועלט!",
        "Mo ki O Ile Aiye!",
        "Sawubona Mhlaba!"
    ]
}
